files:
  - source: '*.xml'
    ignore_settings: 1
    ignore:
      - About.xml
      - LoadFolders.xml
    translation: /**/%language%/%original_file_name%
    content_segmentation: 0
  - source: '*.txt'
    translation: /**/%language%/%original_file_name%
